modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="wariumapi"
version="1.0.1"
displayName="Warium API"
authors="TheMCGuy101"
displayTest="MATCH_VERSION"
description='''
Example mod description.
Newline characters can be used and will be replaced properly.
'''

[[dependencies.wariumapi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"
